### ISSUE TITLE
FG: Failover & TCP Soft Errors?

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#1055]
Added based on TAPS WG input from FG:

* Section 4.3.3. Failover

I haven't recently checked what's the status of current TCP implementations. But at least at some point in time there are some that would failover more quickly based on notifications from the network (e.g., ICMP errors). see: https://datatracker.ietf.org/doc/html/rfc5461

**Comment by mwelzl** [comment]
Regarding the behavior of the underlying protocol, the text here says "Failure of a leaf node is determined by its protocol negotiation failing or timing out; failure of a parent branching node is determined by all of its children failing."

I would say: whether the protocol negotiation fails due to a timeout or because of something like an ICMP message is internal to TCP and doesn't matter for the entity taking the decision above, and hence not relevant for this text.

Thus, my suggestion: close this issue with no action.  Or am I missing something?

**Comment by mwelzl** [comment]
With three people (including myself) agreeing that this can be closed without requiring a text change, I now go ahead and close this.
