### ISSUE TITLE
Should we use normative language for restricting multiple identifiers on a endpoint?

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-tapswg/api-drafts#1093]
https://github.com/ietf-tapswg/api-drafts/blob/9266fbe3b55966edaf4013e755d46ae6f0fed8de/draft-ietf-taps-interface.md?plain=1#L720-L721

This seems to me as a strong claim without using normative language. Shall we use normative language here?

**Comment by gorryfair** [comment]
Agree, although then I think we need to explain "set" so that we create an RFC2119 sentence with meaning when read on its own. Is this anywhere near:

An Endpoint MUST NOT set multiple identifiers of the same type. 

And... is the /that is/ correct? or is this an example of something that is not allowed?

**Comment by mwelzl** [comment]
I'd say it's an example, although also the most likely such case. Suggest: replace "That is," with "Thus,"

**Comment by zaheduzzaman** [comment]
If this is just an example then lets just be explicit about it.
