### ISSUE TITLE
Wording nit: does it preclude a multicast group endpoint?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1261]
From the review by Éric Vyncke:

## Section 3

`from a Remote Endpoint` does the use of 'a' preclude a multicast group
endpoint ?

**Comment by gorryfair** [comment]
Not here in my thinking, because there is only one sender.

But.... there is a problem here:
* Remote Endpoint: The Remote Endpoint represents the application's identifier for a peer that can participate in a transport connection; for example, the combination of a DNS name for the peer and a service name/port.

If the endpoint is a group, then this might read differently, e.g., 
* Remote Endpoint: The Remote Endpoint represents the application's identifier for a peer or multicast group that can participate in a transport connection; for example, the combination of a DNS name for the peer and a service name/port.

**Comment by gorryfair** [comment]
Note - I added a query to arch as a PR to fix remote endpoint there: #1269

**Comment by csperkins** [comment]
We use the multicast group as the `RemoteEndpoint` when sending. When receiving:

> Calling Listen on a Preconnection with a multicast group specified on the Remote Endpoint will join the multicast group to receive Messages. This Listener will create one Connection for each Remote Endpoint sending to the group, with the Local Endpoint set to the group address.

so I don't think this is a problem.

**Comment by gorryfair** [comment]
OK, this issue can close PR #1269 is approved and  merged.
