### ISSUE TITLE
Why not QUIC?

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1320]
From the review by Robert Wilton:

(copy+pasting the table of contents section 10)

I was surprised not to see QUIC included in this list of specific transport
considerations.  Are there no specific considerations for QUIC, or is it out of
scope?

**Comment by gorryfair** [comment]
I suggest it is out of scope for this spec, and perhaps we should state what transports are covered by the Interface spec.However, I think we ought to state the TAPS Architecture does apply to other protocols  as future specifications include them. and explicitly mention as an example, QUIC.
(by the way I'm adding the tag of Arch - because I'm think this the statement belongs there.

**Comment by gorryfair** [comment]
... and had not finished: 

Arch already shows QUIC in a diagram, but never says anything about whether QUIC and other bindings will appear in the interface spec it then goes on to describe, indeed this says:

"The Transport Services API {{?I-D.ietf-taps-interface}} defines the interface for an application to create Connections and transfer data. It combines interfaces for multiple interaction patterns into a unified whole (see figure 2). By combining name resolution with connection establishment and data transfer in a single API, it allows for more flexible implementations to provide path and transport protocol agility on the application's behalf."

- I suggest we need a short para specifically saying that {{?I-D.ietf-taps-interface}} defines generic functions and also the protocol-specific mappings for TCP, UDP, UDP-Lite, .... .Future documents could define similar mappings for QUIC, etc.

**Comment by mwelzl** [comment]
I agree that this belongs into arch, and probably only there, so for now I removed the "Implementation" label.

**Comment by gorryfair** [comment]
OK, I will add this.
