### ISSUE TITLE
Bounds on send and receive rate

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#1347]
From the review by Lars Eggert, COMMENT part:

### Section 8.1.8, paragraph 4
```
    Numeric values of these properties specify an upper-bound rate that a
    transfer is not expected to exceed (even if flow control and
    congestion control allow higher rates), and/or a lower-bound rate
    below which the application does not deem it will be useful.  These
    are specified in bits per second.  The enumerated value Unlimited
    indicates that no bound is specified.
```
Over what timescale, or is this supposed to apply to instantaneous
bandwidth? Because an app can control how much data over time to feed
into a connection, but cannot usually know what send rate that
results in.

**Comment by gorryfair** [comment]
Perhaps in general the comment is very true. However, I think there are applications that can know an upper-bound rate or lower-bound rate. Some video applications have more clear bounds; some bulk transfers can propose a minimum rate - rather than incurring execessive time, etc.

My suggestion would be:
* to prefix this by saying when an application can identify specfic bounds...
* to explicitly add that the default value is Unlimited.

**Comment by mwelzl** [comment]
The default value Unlimited is really as explicit as can be:
https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-bounds-on-send-or-receive-r
