### ISSUE TITLE
Replace long author lists with editors

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#184]
The RFC Editor has become rather strict in implementing the 5 author limit for drafts:

This document has more than five authors listed, which is considered excessive under normal circumstances. If you plan to request publication as an RFC, this will require additional consideration by the stream manager (for example, the IESG), and publication may be declined unless sufficient justification is provided. See RFC 7322, section 4.1.1 for details.

We should update these for -01

**Comment by gorryfair** [comment]
In cases where one or two authors are collating stuff, then this is certainly correct. I'd need convincing this is true for at least some of the author list - in cases where more than 5 authors need to be in RFC-Ed review, I was always told the process could be over-ridden, where the author team needed that level of interaction with the process.

**Comment by mwelzl** [comment]
The phrasing in RFC 7322 is "If there is a request for more than five authors, the stream-approving body needs to consider if one or two editors should have primary responsibility for this document, with the other individuals listed in the Contributors or Acknowledgements section."   - "if there is a request ... needs to consider" doesn't seem to me like a strict "MUST be like that", indeed.

I'm also quite unhappy with the idea of moving to an editor - author mode. I think that for both the API and the implementation draft (I didn't really follow the arch. one), all authors have been making truly substantial contributions across the whole thing, more than just "send me a few paragraphs and we'll include them".

**Comment by tfpauly** [comment]
@mwelzl I don't see how having an editor-author model reduces the perceived contribution of the authors. For documents like those in the QUIC WG, there are many people I know who are extremely active as authors, who I recognize are primary contributors, despite not being editors.

I raised this issue since its a point that Aaron brought up, and I agree that it gets fairly hard to read a document when the first page is half taken up with lines of names.

**Comment by mwelzl** [comment]
@tfpauly - well I disagree about the first page being "half taken up" with this, and about the document getting hard to read; it also seems that the rule that Aaron was concerned about is not strict, plus it seems that the large majority of us is in favor of keeping it as-is.

**Comment by gorryfair** [comment]
I still don't think this is the right thing to do.

**Comment by philsbln** [comment]
@tfpauly For the academic contributors, author vs. being in the acknowledgment section often makes a big difference for internal and project evaluation – moving it (from an administrative perspective) from a project we get credit for to a fun/hobby project.

**Comment by csperkins** [comment]
Agree with @gorryfair, @mwelzl, and @philsbln: moving authors to a contributors section is problematic and suggests a lesser contribution

**Comment by adfalk** [comment]
In the last 10 years only 3 RFCs have been published with 10 authors.  We need to revisit this issue as support of the wg and the AD will be needed to request publication with an author list this long.

**Comment by gorryfair** [comment]
I'm going to draft a case here for others to look at and allow us to comment, if needed this can be into a PR.

Why do the core TAPS docments have a long author list?

The TAPS work on the three core API drafts has been a 7-year journey to make a new kind of specification - this is an API, and unlike many protocol specifications it actually requires a large team to closely work on this together. I believe there is a  very good case that this short series of specs are unique in several ways.

This is intended to be well-argued case for an exception - as permitted by the process - not a precedent:  Even it TAPS,m we’d expect future documents to be focussed on parts of the stack (as was the case in early TAPS documents).

First: it forms the first IETF transport API, something not previously published by the IETF. An integrated team-based approach was recognised as important from early in the document development and was discussed a number of times. The resulting team brought drew from several previous projects, important initial contributions from two EU projects (NEAT.MAMI), independent work at TU Berlin and Glasgow and independent work at Apple, and a small number of others. Each author continues to play a key part in shaping the way the final document is structured, while bringing necessarily expertise across a wide area of topics(see github activity, and IETF meetings… with 8 meetings per year with < 450 issues and over 300 PRs) to draw expertise on a wide range of subjects. Things have evolved many times, but this was essentially a team effort - not an editorial  process to draw together contributions.

Second, the topics span a very wide set of expertise - even for the IETF, and rather than make many documents, we purposely focussed on three closely linked documents to cover:
* Understanding of applications use of transport
* Architectural design
* Privacy, Security and Policy in the stack
* Trends in modern API and variations between programming languages, and use of callback, events, etc.
* Detailed understanding of differences between the IETF transports
* Understanding of STUN/ICE and Rendezvous
* Understanding of NAT, details of using of IPv4 and IPv6
etc

Third, as the document passes through IETF review, IESG review and RFC-Ed the present authors have a commitment and style of working that is effective and ensures that details are not overlooked. I don’t think this close working is typical of the IETF process with which I am familiar, and likely is because of the nature of these specific specifications. I don’t expect many IETF documents had such a breadth of expertise and were developed in this way, at least not within transport.

Overall, this represents been a major investment by the entire author team. Normally the underpinning research contribution can be published in Journals, etc. However, in this case, people have been actively working on refining the spec for several years after their research to bring a consistent and new type of API to the IETF, and the final outcome is this spec. At least where I work, this contribution is only recognised by the University when I am an author (I personally do contribute to many, many, other documents at the IETF - I understand that these won’t be counted by my employer, which is the way it is - however this is a core piece of work and it is very important to see this acknowledged.)

.

**Comment by csperkins** [comment]
I'd like to strongly support Gorry's points. These drafts are very much a team effort, with much closer and more sustained group effort than I've seen for many other drafts in the IETF. Changing the authorship at the last minute, to exclude people who've put tremendous effort into writing, checking, implementing, and testing these drafts is both ethically dubious and highly inappropriate. 

If we want people from different backgrounds to participate in IETF, we need to give them incentives and credit when they do. For academics, that means authorship of the drafts they write. Like Gorry, I contribute to many IETF drafts – often without credit – because it's the right thing to do, to improve the Internet. I accept that as the nature of IETF work. But, when I've spent many years working on a set of drafts, helping fashion the design and writing extensive parts of the text, that needs to be acknowledged by co-authorship.

**Comment by mirjak** [comment]
I agree that there are good reasons to keep a large author list. However, we should probably still review the author list before we submit. Can't remember how we actually "distributed" the authors when we moved away from the initial set of documents but not sure that still maps with the contributions each authors made on each document.

**Comment by theri** [comment]
I think this issue has now been resolved: We have reduced the authors on arch and impl to 5, and we have arguments for keeping the interface doc at 7 authors.
So I'll close this issue.
