### ISSUE TITLE
Connection.Receive(minIncompleteLength, maxLength)

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#221]
I don't think having the receive parameter "minIncompleteLength" and "maxLength" is the right approach here. 

"minIncompleteLength" is rather a configuration for the transport layer to decide when to create a callback receive event, therefore providing it together with receive() is too late. It's probably a Connection P*. 

"maxLength" seems to superfluous because ideally receiving is a zero copy operation and as the transport as stored the data already somewhere it doesn't seem useful to set a limit here. Of course again there probably needs to be a system config and or connection P* somewhere. If at all this seems rather like an implementation detail to me (that may or may not be discussed somewhere  but should not be part of the actual API spec).

**Comment by tfpauly** [comment]
I disagree that the minimum incomplete message length for a single invocation of Receive should be a connection P*—we use this quite often to be different for each Receive. Say, you want to receive exactly 4 bytes to read some header value, and then you want to read a minimum of 1KB, and up to the length of that message, etc. The point of minimum incomplete length is that you really don't want to be signaled or woken up as an application at this stage of your processing until N bytes are available. If you ever need to read a little bit (which almost all apps do), you'd have to set your connection P* to 1, and then you can't get this receive low water mark behavior.

The same goes for the max length. While the max length I could ever receive maybe could be a system limitation, there are two very important functions for specifying it per Receive: I may not be able to handle parsing more data than a certain amount right now (I want to read up to a point, which will determine which code module I need to pass the connection to in order to do further processing); or I want to communicate back pressure down to the transport stack. If I don't have a max length on a Receive, do we assume that the Receive is asking for as many bytes as possible, and to read them all into process memory at once? Yes, maybe you have zero-copy from the library to the app (which itself is not a guarantee), but you almost certainly cannot guarantee zero-copy from the driver, and something needs to also tell TCP when to close its window.

**Comment by tfpauly** [comment]
I agree that the usual case is that you want to Receive a complete message. In that case, you don't specify (minIncompleteLength, maxLength) at all! It's equivalent to saying UINT_MAX for both values. The only time that an application would specify the min/max lengths is for receiving partial messages. So, since this is predicated on the application wanting to handle partial data.

Also, with regards to copies... if our message is very very large (many gigabytes of a file, in which case the app may be wanting to stream it in partial chunks), then we cannot not simply deliver a buffer of the entire message to the application to read out of. The amount they read at a time, via the invocations of Receive(), determine the flow control on the stream.

**Comment by mirjak** [comment]
I'm still not happy with the concept of partial messages. At the moment it seems nearly more natural to send partial messages than full messages (especially as the property is called "final" instead of "partial"). Which goes back to the other discussion on order and final, and I still don't really see why you need partial messages at sender-side. The application can just decide to segment any big message in any way call it a "chunk" of a message or whatever and provide it as a message to the transport. All you need, if at all, is telling the transport that there is a dependency.

For the receiver side, if you don't know the message boundary, you can only provide random chunks (and should tell the upper layer that it is a random chunk). With providing a length to the transport, you can reinforce to received messages at the boundaries if you have this information. If that is what you want, I think we a) need only one length and b) should call it that way.

**Comment by tfpauly** [comment]
If the transport API provides support for message boundaries, and those message boundaries are transmitted the other side, the sender may need/want to stream in a single message in multiple chunks (partial messages). Requiring the application to use some other understanding or mapping of messages really isn't ideal.

To be very concrete:

Let's say I have a protocol that supports independent sending and receiving of messages, like how an HTTP message would get its own QUIC stream. If I have a particularly large request or response (megabytes or gigabytes) I may not be able to send it all at once; and even if I can, I may want to be able to pace the data.

In another case, let's say I have a simple TLV message protocol on top of TCP. I want to treat a single TLV as a message for both sending and receiving. Maybe most of the time I have small messages that I write atomically, but a couple of the messages are large, or not generated as one piece of data (maybe because I'm receiving it in pieces off of another network connection). It's convenient to be able to push data in in pieces.

**Comment by britram** [comment]
@mirjak are you okay closing this one?
