### ISSUE TITLE
Do we need to have an explicit/separate object for Listener?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#254]
Or is a Listener just a Preconnection that is configured in a certain way?

**Comment by tfpauly** [comment]
Listener is its own object for sure, in my mind. A Preconnection just exists as a configuration/description—it doesn't register anything.

The fundamental part of a Listener is that it actually binds to the local ports on the various paths that are applicable. A Preconnection is a potential Connection or Listener, but until you actually initiate or listen, you don't know if you'll hit some error due to someone else on the system having registered on the same port, etc.

**Comment by mirjak** [comment]
Yes, I'm pretty sure that every implementation will have an listener object; my questions is rather is that something that needs to be exposed as an own object and does that need to be described in the arch doc? I'm not sure here but I'm also okay keeping it but in that case we need to fix the diagram (as the listener is created from a preceonnection when you call listen).

**Comment by tfpauly** [comment]
Agreed that the diagram needs updating, ala #257

**Comment by tfpauly** [comment]
Fixing API to align with arch #301
