### ISSUE TITLE
Add re-initiate() call for voluntary connection migration 

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/api-drafts#270]
In #38 we discussed several reasons and ways how multipath and connection migration may be used to address changing application requirements. While most of the use-cases are better captured by a connection pool (see Issue #266 and #38), some might really want to change an existing connection. Therefore, we should add something like re-initiate to perform this operation.

**Comment by mwelzl** [comment]
The discussion in #38 ends with @gorryfair saying: "...this drfat needs to leave the path selection properties in Pre-Establishment state - It's always possible to be more exotic and there are clearly cases where this will in future be useful. However, I am really keen to avoid making this API byzantine in complexity, and this is an area where I fear this is great PhD material and poor standards." which got a thumbs-up from @tfpauly. Then, @philsbln wrote: "I came to the conclusion that this kind of functionality is best capsuled either in a connection pool (see Issue #266) or in some migrate/re-initiate call for most practical use cases."

Here you're asking for the re-initiate because some practical use cases don't seem to be captured by the connection pool idea. Could you give us examples?

**Comment by mwelzl** [comment]
I'll try closing and hope that all is well  :-)     I mean, it was even marked as "science fiction"...

**Comment by philsbln** [comment]
``Connection Pool`` solves everything that communicates in a request/response pattern, e.g., HTTP. This is the "automagic" mode.

``re-initiate`` is needed if one really uses a stream and wants to manually migrate it, e.g., explicitly switching to a different address for SCPT or open a sub-flow for MPTCP. 

Still two different issues.

**Comment by mwelzl** [comment]
Ok, understood - fine to keep discussing this as a separate issue. However, I'd still like to close it: can you tell me very concretely when / how you need this?  FWIW, address switching in SCTP is handled *by* SCTP, and the API that gives such per-sub-flow control for MPTCP hasn't gone further in the MPTCP group IIRC.

A concrete problem I see with this is: what are the real semantics of re-initiate, regarding the old Connection? That all data is perhaps lost, or perhaps not? How much must I retransmit on the new connection? Can there be duplicates?

It seems that these things must then be handled by the application, if it really needs to such functionality. Thus, could this be part of what a framer does?
