### ISSUE TITLE
 Section 4.2.1 - Transport Properties

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#316]
Section 4.2.1: “Allow different components of a TAPS implementation to pass Transport Properties, e.g., between a language frontend and a policy manager.”
- Question??? : Would it also be OK to include a suggestion that these could also be retrieved from storage, e.g. “Allow different components of a TAPS implementation to pass Transport Properties, e.g., between a language frontend and a policy manager, or to retrieve a list of properties from a file or other storage.”

 Section 4.2.1.:
Are the definitions of “should” actually “SHOULD”, I don’t otherwise understand the meaning of the lower case should. Actually, why is it SHOULD not MUST for the IETF-specified class?

**Comment by philsbln** [comment]
I am in favour of adding the suggestion of adding a suggestion of using this representation on stable storage, but shouldn't it be rather "or as a representation of properties retrieved from a file or other storage."

I chose "should" over "must" here because I feared  defining protocol specific properties for all important IETF protocols may creep in as a dependency for publication of this document otherwise.
With regarded to the casing, this really must be a SHOULD.

**Comment by britram** [comment]
fixed by #335
