### ISSUE TITLE
Section 7 default

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#319]
Section 7.3.1:
- The word “lifetime” appears several times in the architecture document. I am unsure whether any of these uses are the same as the use here. This would be helped (of course) a little, if this section were renamed as “Message Lifetime”
- What is the default? if any?
——
Section 7.3.2 
- What is the default priority?
- Interesting question, but I suggest it could be useful to still have a default even if the meaning and range are varying. If the default were, say, “100” then anything less than 100 is less priority and anything more is more than default priority. That’s useful if I supply no param in one connection and then supply a param in other connections.
—
Section 7.3.3. Ordered
- I think this needs to default to safety: i.e. TRUE - Required.
—
Section 7.3.4. Idempotent
-I think this needs to default to safety: i.e.  “FALSE”.
—
Section 7.3.5. Final
- I think this should default to the most common: i.e.  “FALSE”.
—
7.3.7. Reliable Data Transfer (Message)
- this should default to something.
—
7.3.9. Singular Transmission
- What is the default?
—

**Comment by mwelzl** [comment]
PR #330 addresses this. Some details below:

Regarding "lifetime", the use is indeed different. However, all these occurrences seem to clearly refer to a different thing than the Message Property from context (e.g., by saying "the lifetime of a connection"). Renaming this into Message Lifetime seems clumsy and inconsistent (as in: why are all the other Message Properties not prefaced with "Message"?), so I decided to leave this as it is.

Regarding 7.3.7: I chose "true" as a default because it is probably the most common (and allows TCP as a protocol choice).

Regarding 7.3.9: I chose "false" as a default because it is probably the most common (and allows TCP as a protocol choice).
