### ISSUE TITLE
Add explicit protocol selection.

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/api-drafts#324]
This issue was discussed in the May 2019 interim.

Some Applications may really need a specific protocol and can not rely on the transport system  to choose an appropriate one.

**Comment by gorryfair** [comment]
Agreed. Although that does not mean we have to or even should standardise a way to express this.

**Comment by philsbln** [comment]
I guess we should standardise a way to express this, to avoid ossifying the selection properties on the assumption "combination x1 x2 x3 is guaranteed to give you YTP".
Nevertheless, we should discourage its use by having profiles as a more convenient alternative.

**Comment by GrumpyOldTroll** [comment]
I agree with @philsbln; if we do not provide a standard way to express this, the workarounds people will end up using when they need this will be much worse for taps's adoption and goals than giving them a way to express an explicit need for a specific protocol.

Even though I also see that providing this will sometimes result in apps using the same old protocols instead of making use of new and better ones, we can't get rid of the need for picking specific protocols in some cases, and we can't serve the need by ignoring it.

IMO the solution is to accept that developers will make the wrong choice on this sometimes, and to make it so that there's a good 1-line fix when they realize it.  Making it harder to express won't prevent the mistakes, it'll just make the mistakes harder to unwind.

**Comment by tfpauly** [comment]
I agree that apps need to be able to restrict this. That has been part of the architecture from the start, although the API doc doesn't specify how to do it.

Based on the architecture, my suggestion is:
- Specify a set of allowed protocol stacks if you want to restrict; if you leave it empty, we choose for you
- The protocol stacks are composed of per-protocol options, to express "if you use TCP, use these TCP flags"

**Comment by philsbln** [comment]
Please take a look at PR #327 wether it addresses the first of @tfpauly's points.

For the second one, I think the current design with protocol specific properties is sufficient, as protocol specific properties on a preconnection are ignored for other protocols.

**Comment by britram** [comment]
Suggestion from the authors' meeting in Montréal: leave this underspecified in the standard, and state that implementations SHOULD provide the application a way to override transport selection and instantiate a specific stack, but make this functionality explicitly non-portable.

**Comment by britram** [comment]
(also explain why you may want to force a stack per @gorryfair)

**Comment by britram** [comment]
Michael: figure out where to put this. Note that selection properties are also used for listening, and that (especially servers) might want to provide explicit protocol stack selection, but that methods for explicit selection are out of scope for the abstract interface. michael suggests this belongs up top, near/in intro.
