### ISSUE TITLE
Consider message send API that takes padding policy as input

### ISSUE THREAD

**Issue by chris-wood** [ietf-tapswg/api-drafts#334]
One might want to send a message M as a multiple of size B octets. Since padding is (increasingly) supported by transports, this should be something a TAPS implementation provides. Moreover, applications should ideally be able to specify their padding policy.

**Comment by gorryfair** [comment]
I don't agree this is a need in the basic API. 

While there are good reasons to introduce padding - and it solves some issues , I suggest this is often something that can be done by the app or library using the TAPS system. I don't think this is a core application need, and it is debatable whether this is something that should be used by default in applications. 

For example: I'm not convinced that CHAFF packets on their own provide much protection from machine learning of traffic characteristics. I am also concerned that routinely padding data is a method that significantly reduces performance over some types of path (e.g. it makes inefficient use of radio resource).

**Comment by chris-wood** [comment]
> I suggest this is often something that can be done by the app or library using the TAPS system.

Of course! I do not mean to imply this should be the default case. What I'm suggesting is that the API let clients make use of padding mechanisms provided by modern transports. Punting this to the application is certainly possible, and QUIC's a good example of what happens when that's done. 

All that said, this could certainly be something discussed in the implementation document. I'm not advocating for it to be in the API document (though I see why the title of the issue might suggest that :)). 

> For example: I'm not convinced that CHAFF packets on their own provide much protection from machine learning of traffic characteristics

It's an open area of research. Fixed-sized and adaptive padding can, for example, help quite significantly in some cases.

>  I am also concerned that routinely padding data is a method that significantly reduces performance over some types of path (e.g. it makes inefficient use of radio resource).

Certainly. It's a tradeoff.

**Comment by philsbln** [comment]
I see a value in being able to influence padding from the application, but am nit sure what the right way of exposing this control from the API is. This gehts even more complicated as most use-cases I see are somewhat security related:

 - Amplification prevention (require messages that trigger large responses to be large themselves). This is much easier if the application can instruct the transport system to pad to the MTU estimate somewhere – especially because it relieves the application from taking size changes by the encryption into account.
- Traffic obfuscation – especially if packet sizes provide too many insights.

While the first one could be a message property, the second one should definitely be a security property and may ask for a certain level of protection.

**Comment by britram** [comment]
Considered.
