### ISSUE TITLE
"Events" versus "Callbacks" for security-relevant asynchrony

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#347]
The TAPS architecture uses Events for all asynchronous happenings, except the trust and challenge callbacks. I think this is the right way to do things but I'm not sure because the callbacks are slightly underspecified at the moment -- callbacks are distinct from events because events are fire-and-forget from the TAPS system's PoV, while callbacks might fail (and the system and transport stacks react to that failure).

This raises a few questions:

1. Should we more explicitly specify callbacks in §5.3.2? (I think yes)
2. Should we add the concept of callbacks to the architecture? (I'm not sure, maybe?)
3. Should we generalize events instead to allow them to have a boolean return? (I think no)

**Comment by MaxF12** [comment]
I think it is a good idea to keep them separate and specifying them more explicitly. 
We should also give the documents a pass with that differentiation in mind, for example in Sec. 2 of the API it says that callbacks are a possible way to implement events.

**Comment by tfpauly** [comment]
1. Yes, we should specify callbacks in the API document
2. No, I don't think the architecture needs a formal callback definition specifically BUT it should be updated to remove callbacks from the list of events, and just say that the API lets the application know when certain actions are completed.
3. I'm not clear on the boolean return here... in general, I don't think the events need to be generalized?

**Comment by britram** [comment]
"boolean return" in terms of allowing the application to signal back that an event was not / could not be handled (which is the reason callbacks are separate).

**Comment by philsbln** [comment]
As we were very successful in normalising concepts and avoiding to add similar but slightly different things, I strongly prefer "events" over "events+callbacks".

Instead of a boolean return, I prefer either saying these events may use a specific abort mechanism or need to acknowledge the passed values (and leave it to the implementation whether acknowledge means retuning a boolean, calling a function, writing to a channel or not throwing an exception).
