### ISSUE TITLE
-impl should say more about use of ALPN

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#362]

**Comment by theri** [comment]
Maybe I'm the only person who hasn't been following this, but could you provide a reference, please?
Even saying which IETF 106 session this was discussed in would help.
Thanks!

**Comment by philsbln** [comment]
ALPN discussion took place in QUIC on Tuesday. The basic question was  is an ALPN defining the "next" protocol or the whole protocol stack. so is it "h3" or "h3q1".

Depending on how this discussion goes on, we really have to think whether ALPN is mostly derived (otherwise manually set as a tls-specific transport property) or becomes part of the endpoint.

**Comment by gorryfair** [comment]
I heard. That sounds like we should avoid toon much text on this topic in these IDs.

**Comment by mwelzl** [comment]
I agree not to add too much shaky stuff to our drafts.
So... should we or should we not?

**Comment by abrunstrom** [comment]
Maybe tag it as future work and close it?
