### ISSUE TITLE
Use of normative language in Arch

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#418]
At some point we added normative language to the arch doc but only changed cases where use of upper case keywords are obvious. If we really want to use normative language, we would need another pass and make sure that we identified everything that should be specified normatively.

Alternatively, we could just remove any normative language again and revert respective words back to lower case. I think that would be my preferred solution as a) it is less work and b) I don't think this document necessarily needs normative language.

**Comment by gorryfair** [comment]
Personally, I'd prefer to keep the language - but I agree we ought to review the items.

I'd really like to use REQUIRED, RECOMMENDED, rather MUST and SHOULD - because these are not protocol operation requirements, but implementation requirements to conform.

e.g.: , these properties SHOULD apply to multiple transport protocols.
could be.: , it is RECOMMENDED that these properties apply to multiple transport protocols.

**Comment by theri** [comment]
I think having normative language in there is a good idea because it makes it clearer what criteria we think an implementation has to meet or to give guidance on what to prioritize to implement.

In the current draft, there's two places in which I find the normative language odd and maybe misplaced though:
- Section 4.1: "Events MAY also provide opportunities for the application to interact with the underlying transport by querying state or updating maintenance options." - Maybe this should be rephrased or the MAY removed? Clearly events _are_ an opportunity to exchange information, which an implementation MAY or may not take.
- Section 3.2: "A Transport Services API MUST allow applications to define such requirements and constrain the system's options." - This seems to be oddly unspecific for a MUST: There MUST be some way to define some constraints, but what exact constraints is undefined? Also, this is in addition to minset, and I thought MUST should mostly cover minset to limit scope creep.

**Comment by gorryfair** [comment]
I agree with bot of those Theresa! I don't think we need keywords for either of these clauses.

**Comment by theri** [comment]
Following our discussion during the interim and having thought about it a bit more, I'd be okay with not having normative language in the Architecture document, as long as we make sure that it still clearly says what has to be implemented (i.e., support for minset), and as long as we still clearly warn against unsafe fallback for security protocols and such. But I guess that for me, changing the words to lower case would be enough.

However, if we do that (and maybe even if we don't), we need to make clear that the API document actually contains ALL the normative language we need. For example, I'm not seeing anything on security protocols fallback in the API document yet.

**Comment by gorryfair** [comment]
I admit I misunderstood what Mirja's comment was. Gorry was Sorry. - this was the benefit of some discussion. This has made me realise:
* The edits in Tommy's Pull Request are likely appropriate - the way the text evolved was not useful after all. I will read the whole ID carefully and...
* My hope of good requirements requires much more focussed text - I take the opportunity to propose a concise requirements section along the lines of what emerged in the Interim. Coming soon.

**Comment by britram** [comment]
I'm merging #502 in advance of the 107 draft deadline. There's one question as to how hard we should push minset at the arch level, which I think is a point for wider discussion, and a few nits which can be picked up after the draft lands.

**Comment by gorryfair** [comment]
Proposed new requirements section in arch opened as new issue #519. If we agree to consider that, this issue can now be closed.

**Comment by britram** [comment]
#519 is the new issue for this.
