### ISSUE TITLE
Configuring MP active/passive

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#437]
For MP use we have the following option: Disable, Handover, Interactive, Aggregate. 

I think the option as not well defined (except Disable). Maybe the following is a bit better:

Handover: : The connection should attempt to migrate to a new paths when interface availability changes and performance of the currently used path decreased below a certain threshold. This threshold is implementation-specific.

Interactive: : The connection should attempt to use multiple paths in parallel in order to always select the best path available or at least achieve about the same aggregated bandwidth as provided by the best of the available paths. This can be achieved by using coupled congestion control as proposed in {{?RFC6356}} for MP-TCP.

Aggregate: : The connection should attempt to use multiple paths in parallel in order to maximize bandwidth. That usually means that independent congestion control instances are used on each path.

I also proposed another option:

Redundant: : The connection should send the same data on two of the available paths. A message property could be used to indicate which messages should be send redundantly.

And further I think we also need a configuration option to indicate when/if a new subpath should be opened. I think there are four options: 

Never-passive (rely on other ending opening new paths and never send new available IPs),
Never-active (rely on other ending opening new paths but signal send new available IPs), 
Immediate (open new path when IP because available locally or provided by other end), 
On-Request (application needs to indicate).

Note that there is also rfc6897 specifying a rather different interface...

**Comment by abrunstrom** [comment]
There are many options for MP. I think the idea with the current proposal was to start simple and stick to options that have deployment experience. As I understand the currenr proposal Aggregate is the option that uses both paths with coupled cc. I do not think we should have an option for uncoupled cc. Interactive is not targeting bulk traffic and will try to use a single path unless performance drops too much. So that is the most fuzzy.

**Comment by gorryfair** [comment]
Handover - sounds like what is called failover in many places. Can we call failover?

I'm concerned by "interactive" - This is fuzzy indeed. Can we manage without this?

I don't like "redundant" - true you can do this, but then when you have different paths; CC; etc you can introduce issues - do we have experience of this - is this a great thing to do below the transport, rather than in  the App... I am quite unsure.

**Comment by tfpauly** [comment]
Interim discussion: generally not wanting to expose redundant.

Exposing alternate addresses to the peer and actively migrating is likely a separate property that we should specify.

**Comment by tfpauly** [comment]
Also review description text on enum instances
