### ISSUE TITLE
Why do we use functions to set security parameters...

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#440]
... while we use (property, values) pairs to set other properties?

Is there a reason for this? Otherwise I suggest we agree to one interaction model!

**Comment by mirjak** [comment]
Related I also think this text isn't really that correct:
"Security decisions, especially pertaining to trust, are not static.
   Once configured, parameters may also be supplied during connection
   establishment.  These are best handled as client-provided callbacks."
You can update some security parameter anytime during the connection using the same interface as before. However the two callbacks we have defined require actually actions that follow an event, so they have to be callbacks.

**Comment by mwelzl** [comment]
"However the two callbacks we have defined require actually actions that follow an event, so they have to be callbacks."  - that's it, these need to be callbacks. @britram made them like that because using them requires a tighter interaction model. See issue #347.

**Comment by tfpauly** [comment]
As discussed in interim, Security Parameters are a bit different from selection properties. We should review the security parameter interface, but it will likely be independent.

**Comment by philsbln** [comment]
I did a closer review on these and there are two main differences between Security Parameters and the other Preferences / Events:
 - Use of individual calls on security parameters instead of add with keywor. These could easily be integrated, e.g., by turning ```SecurityParameters.AddCiphersuite(…)``` into ```TransportParameters.Add(cipher-suites, …)```
 - Use of Callbacks instead of Events – closed as Issue #347. Despite there is no technical reason to not turn the Security Callbacks into events, events that "need to do something", i.e.,  
 accept, reject, or return an identity, really look wired.
Let's discuss which way to take this one forward:
 - Leave as is
 - Align the interface of SecurityParameters to the Transport Parameters, but keep them as a separate object and leave SecurityCallbacks as they are
 - Integrate the interface of SecurityParameters into the Transport Parameters, but keep SecurityCallbacks roughly the same
 - Integrate the interface of SecurityParameters into the Transport Parameters, make SecurityCallbacks more event-like.

I am happy to make a PR for whatever we decide, but not for all of them.

**Comment by tfpauly** [comment]
We can do the minor option to change AddCiphersuite to Add(ciphersuite...)

**Comment by tfpauly** [comment]
Maybe add clarification text to say that these are pre-connection only parameters

**Comment by tfpauly** [comment]
Consider cutting cache lifetime, etc, from this list

**Comment by gorryfair** [comment]
We really should explicitly add a sentence to clearly say that the security functions are configured using add functions and not via Properties. This is so useful to say, so that someone does not come along and do this because they think we just didn't see this.

**Comment by philsbln** [comment]
closed with #594
