### ISSUE TITLE
Questions on Connection Groups

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#441]
A couple of questions we might want to address regarding Connection Groups.

1) Can the application query the interface to figure if two connection in a group share the same transport connection but on different streams or not. Is that useful? I thinks we should explicitly say that if a multiplex protocol is used, calling Clone() MUST create a new stream (and not a new connection).

2) If a new connection is created by a Listener it is automatically part of a group, right? Can I detach that connection from the group? Otherwise how can I change a property only for that connection? Isn't is actually confusing that these connection are grouped?

2) Should we add a pointer to coupled congestion control (rmcat) in that section?

**Comment by mwelzl** [comment]
1.
"Can the application query the interface to figure if two connection in a group share the same transport connection but on different streams or not." - no.

"Is that useful?" - Good question. The behavior attained with coupled cc. for ongoing connections can be VERY similar to the behavior of multi-streaming - exposing such a detail to an application can then lead to unnecessarily protocol-specific code. Then again, it may be useful for an application to know if issuing Clone() comes with almost zero overhead, or if it produces a connection setup on the wire...  so I lean towards "yes, it's useful".

"I thinks we should explicitly say that if a multiplex protocol is used, calling Clone() MUST create a new stream (and not a new connection)."  Fine by me. I think the query that you mention above, then, should be: "is a Connection multiplexing-capable?"  (which will, due to your MUST, translate into "Clone() just means using a new stream").

2.
The difference between Listening with and without cloning is explicit - normally, Listen does *not* produce a Connection that's grouped with some ongoing Connections. Rather, if you WANT to do a "listening clone", you need to issue "Listen" *on* an ongoing Connection, as described in Section 6.4. So it's a different "Listen" call. You can't detach Connections from groups.

3.
Yes! We've also done work on doing this with TCP connections, which works like a charm - I'll insert the coupled cc reference and cite the TCP coupling work too.

**Comment by mirjak** [comment]
I agree with 1): having a query that indicates if a protocol provides multiplexing is probably sufficient (+ the MUST requirement)

On 2) from how I read the document I understood that Connections that are derived from the same Preconnection are clones. If that is not the case of Listeners we need to clarify that and double-check the existing text.

**Comment by mwelzl** [comment]
On 2): that's what I meant in my answer, sorry if it wasn't clear. So what's the problem?

**Comment by mirjak** [comment]
So are you saying Connection from the same Listeners are clones or not? And in each case shouldn't there be a way to also get the other?

**Comment by mwelzl** [comment]
Ahh, sorry, I misread, you talked about "the same *Pre*connection". No, that's not it. If you call Listen on a *Pre*connection, you get a new Connection that is not cloned. That's in:
https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-passive-open-listen

If, however, you call Listen on an *existing Connection*, you get a clone. That's in:
https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html#name-connection-groups

**Comment by MaxF12** [comment]
Just to add, I think its inconsistent that you would call listen() on an connection object. In all other parts of the draft it is only ever used on preconnections.

**Comment by mirjak** [comment]
No that's also not what I was talking about. You call listen on a preconnnection. At some point someone connects and the listener creates a connection (A). Then another (or the same actually) peer connect to your server (again) and the same listener creates another connection (B). Are those connections(A and B) grouped or not?

**Comment by mwelzl** [comment]
The same listener = a listener that was called on a preconnection.
So, in your example, you never called Listen on a Connection, which is semantically different.
So, no, A and B would not be grouped - what makes you think they could be? Noone ever made the Listen call that would do that. What am I missing?

**Comment by mwelzl** [comment]
@MaxF12 that's just a naming thing. Using it on a connection is consistent with Clone() - it's just a different way of Cloning, as a passive instead of active open. We could call it something else - ListeningClone or something. Me, I like it as it stands because, to me, the semantics of "this is spawned off an existing connection" are nicely conveyed by the call being applied to a Connection instead of a Preconnection. But I wouldn't fight about the name if you think "ListeningClone" or something like that is better.

**Comment by MaxF12** [comment]
I agree, its mostly a naming thing but I think there are a few things here that need to be specified which aren't obvious. For example, what happens if you call listen on two connections that belong to the same group? Personally, I would assume that you can't and would get an error if you tried.

I also agree with @mirjak that it is a bit confusing that listener objects, depending on how they have been created, sometimes group connections and sometimes they don't.

**Comment by mwelzl** [comment]
> For example, what happens if you call listen on two connections that belong to the same group? Personally, I would assume that you can't and would get an error if you tried.

Why? The two connections are already both part of the same group, so any of these Listen calls should give you yet another connection that is in the same group. I don't think there's anything indicating any other semantics - such as the error you're describing.

About this being confusing: this is just a matter of having a passive clone. How else would you do it?

**Comment by MaxF12** [comment]
But the listen wouldn't give you a new connection, it would give you a Listener object which in turn would give you new connection(s). Having multiple Listener objects for the same group seems wrong to me.

**Comment by abrunstrom** [comment]
I think this whole discussion suggests that we should indeed use a different name, ListenClone or CloneListen seems the most natural choices to me. Perhaps update the name (and the text accordingly) and see if there is still any points for confusion left.
While calling listen on a Preconnection and a Connection are semantically different, I can see that it is easy to get lost as to what Listen we are talking about in different parts of the text.

**Comment by mwelzl** [comment]
Yes!

**Comment by theri** [comment]
I'm currently reading the Implementation draft again, where Section 4.8.3 talks about listening for multiplexed protocols.
Interestingly, the implementation draft gives different answers to the questions here:

1. The Implementation draft says that "The implementation should allow the application to introspect the Connection Group marked on the Connections to determine the grouping of the multiplexing." So I guess this would change the answer to question 1 here to "Yes", but the interface draft doesn't say how.

2. "Protocols that provide multiplexing of streams into a single five-tuple can listen both for entirely new connections (a new HTTP/2 stream on a new TCP connection, for example) and for new sub-connections (a new HTTP/2 stream on an existing connection). If the abstraction of Connection presented to the application is mapped to the multiplexed stream, then the Listener should deliver new Connection objects in the same way for either case." - It doesn't say what "in the same way" means, but I guess it means "deliver a ConnectionReceived event". The sentence after that talks about querying Connection groups, cited above. So this sounds to me like this text presumes that Connections from new streams on existing connections are grouped, while Connections on entirely new connections are not. But I might be misreading this. In any case, it's not clear. This thread sounds to me like incoming Connections from a Listener created by Preconnection.Listen() are never grouped.

So, I think either we should say explicitly that incoming Connections from that Listener may or may not be grouped (depending on whether there's an "entirely new connection" underlying or whether they're just a new stream), or we say they're never grouped and change the implementation draft later.

However, in that latter case, we'd have outgoing multiplexed connections which are always Connection Groups, and we have incoming multiplexed connections which are never Connection Groups. That doesn't sound right.

**Comment by mwelzl** [comment]
Folks, this discussion and @theri's last comment just made me remember something: I'm afraid we have designed something that just cannot work!

I don't know about QUIC, but I assume it's the same: in SCTP, passively creating a new stream just doesn't exist - a stream comes into being as soon as a new message is sent on it. So, technically, the only thing that really works would be something much more restrictive, as for example:
- having a form of InitiateWithSend as an active clone,
- then, on the passive side, upon InitiateWithSend-cloning, Listener -> ConnectionReceived<Connection> might just fire out of the blue, and only when that happens, Connections are cloned.

**Comment by mirjak** [comment]
If initiate() is supposed to "open" new stream, calling initiate() will not lead to any action on the wire but also create some internal state that the next send of that connection will need a new stream (id). That's fine.

**Comment by mwelzl** [comment]
But is that a clean model?  You call initiate, and because it's just like any other Connection, maybe you expect to possible be able to read something afterwards... but that will never be the case.

**Comment by MaxF12** [comment]
I agree that things get somewhat inconsistent here. When would a Connection created like this fire its ready event? Just immediately?

**Comment by mwelzl** [comment]
Felix Weinrank and Michael Tüxen described in detail how this works in case of NEAT in this paper:
F. Weinrank and M. Tüxen. “Transparent Flow Mapping for NEAT“. In Workshop on Future of Internet Transport (FIT 2017), Stockholm, June 2017.
http://dl.ifip.org/db/conf/networking/networking2017/1570349380.pdf

For their implementation, the answer to your question is "yes". But that's just because we wanted to map Connections at any cost - it comes with the limitation of only being to send (not receive) later, so I'd say this is not fantastic API design. Being able to receive immediately after clone() + ready would require using a signal in the underlying protocol itself - the paper discusses that this could be done with the otherwise unused "Payload Protocol Identifier (PPID)", but the meaning of this signal (as: "I created a stream but I'm not sending anything") would of course have to be known to both sides too, requiring a new standard.

**Comment by tfpauly** [comment]
Opening a connection that just allocates stream ID state should be fine, no? I don't think it's necessarily a problem.

As far as being able to read without sending, that's up to the protocol. No reason some future version of QUIC or similar couldn't support that.

**Comment by mwelzl** [comment]
Well that's true - although, why would future-QUIC do that? Just to support TAPS's communication model? It seems efficient to just implicitly create a new stream by transmitting data on it.

Anyway, at the very least, we should warn the programmer that it may not be possible to initially read on a newly cloned connection, and provide this information as a readable connection property.

Also note that we're now only discussing one aspect of the problem: is it ok to just have an "Initiate".

The other aspect is listening: sure, we could make a general Listen map to things and have warnings and such, but what both QUIC and SCTP would currently be doing is completely different from that. I think it would be better to specify that Listener -> ConnectionReceived might just fire out of the blue, which would also indicate that the first data has probably (with current protocols: surely) already arrived at the stack.

**Comment by tfpauly** [comment]
No, not just to support TAPS! If there was some value in having a stream that a client can open, but not write, and have the server write, which presumably is the case you're concerned about here, and someone has a use case, they can use that.

Even today, you can have a server for TCP that won't do anything until the client writes. I don't see any reason to have the API be restrictive based on particular protocol behavior, when there are cases that do allow that behavior.

**Comment by mwelzl** [comment]
Yes, that's the communication pattern I'm concerned about. It is rare - e.g. pub-sub systems, which in principle follow that pattern, will usually implement an application-level signal from the client to the server that at least says "I'm here". Because this pattern is rare, I doubt that it will be supported in future-QUIC-or-whatever. And that's fine!

The problem is: if I write an application over TAPS and I decide to implement this "I listen, and then I'm the first to send" pattern, then:
- if the underlying protocol is TCP, this will work fine
- if the underlying protocol is a stream of QUIC or SCTP, my application simply gets stuck.

So we should at least put a warning about this case in there, and let an application query if, after Listen, send-before-receive is possible.

**Comment by tfpauly** [comment]
Discussed in interim: this sounds like a property that does protocol selection that doesn't choose QUIC if you require being able to open a stream and then read without sending (TCP allows this, QUIC doesn't).

**Comment by mwelzl** [comment]
The Listen + ListenClone() discussion is moved to issue #508.
I'll make a PR for the outcome above (protocol selection property).

**Comment by britram** [comment]
@mwelzl ping, will the protocol selection property land before the next interim?

**Comment by mwelzl** [comment]
ACK and YES. I had planned to do this today (not happening) or tomorrow (most likely) or the day after tomorrow (sigh, I hope tomorrow will work).

**Comment by csperkins** [comment]
The "client opens the connection but server sends first" model is used in SMTP, right? It's not such an uncommon pattern.
