### ISSUE TITLE
Do we need to make state storage explicit in the architecture and API?

### ISSUE THREAD

**Issue by britram** [ietf-tapswg/api-drafts#45]
Post Sockets had an Association concept, which contained all the information about a pair of endpoints, including security parameters, cached security state, cached path state information, and so on. ISTM that we implicitly decided that this was implementation-specific in the Cambridge meeting (though it lived on in the architecture as Association Cache in §4.2).

It turns out that the Connectable proposed by @csperkins in #42 shares enough of its properties with the non-cacheable bits of an Association that we might want to make this an explicit object in the API again. 

Discuss.

**Comment by abrunstrom** [comment]
I think we should leave this out for v1, I think it is a whole other discussion. On the taps-level there is nothing on the other end so I find it confusing to talk about a pair of endpoints. I am not sure where the term Association Cache came from, but can we call it just Cache or at least something other than Association Cache? I find the term Association very confusing both because it seem to imply a taps counterpart on the other side and because connection and association are very similar to me (just depends on if one use TCP or SCTP :) ). The cache can contain many things, some of them related to a remote endpoint some of them not.

**Comment by britram** [comment]
ok, punting to post-London

**Comment by tfpauly** [comment]
Grabbing this one, as I've been working with the association concept a bunch recently, so I'd like to take a stab at editing the text.

**Comment by tfpauly** [comment]
@britram I'm thinking we should punt this out to -02, that OK with you?

**Comment by britram** [comment]
@tfpauly Yep. basically at this point I'm thinking that -01 is going to be #200 and #201 and we're done.

**Comment by tfpauly** [comment]
@britram I'll try to get something out today; if I don't, then we can skip.

**Comment by britram** [comment]
see discussion on #244 -- I think we (y'all ;) ) should spend some time on this in Bangkok, then take another pass on writing up the consensus that falls out of that.

**Comment by tfpauly** [comment]
Call the connection group a connection context instead?

**Comment by tfpauly** [comment]
Create explicit context to hand to preconnect

**Comment by tfpauly** [comment]
Not passing any context puts you in the implicit context

**Comment by britram** [comment]
On review, this should have been closed with #294 -- closing.
