### ISSUE TITLE
ECN property?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#451]
A bunch or questions on ECN:

Do we want a transport property that indicates that ECN should be requested during the handshake if supported by the selected protocol? Or is the assumption that this is rather a system configuration? Do we need to say this somewhere?

Further I don't think that having ECN markings as a (receive) message property is correct as a message may consist out of multiple packets/datagrams and there could also be packets that don't contain message data at all. I mean the mapping is straight forward for UDP but I guess one could also use QUIC as a datagram only service? And can one use message framers with UDP?

Maybe we should have this a protocol specific property for UDP only? Or we could allow to register events that indicate reception of certain ECN-marked segments? Or we just maintain counters that could be polled by the application...?

**Comment by mwelzl** [comment]
> Do we want a transport property that indicates that ECN should be requested during the handshake if supported by the selected protocol? Or is the assumption that this is rather a system configuration? Do we need to say this somewhere?

I think it's not of concern to the application unless the application has to do congestion control - as in UDP's case - which is probably why UDP is the only transport that exposes ECN..

> Further I don't think that having ECN markings as a (receive) message property is correct as a message may consist out of multiple packets/datagrams and there could also be packets that don't contain message data at all.

Well, in UDP - the only case we have, so far, AFAIK - it is associated with a packet, which becomes a Message. As you say, the mapping is straightforward for UDP - but e.g. QUIC as a datagram only service shouldn't expose ECN because QUIC is congestion controlled.

> Maybe we should have this a protocol specific property for UDP only?

We could do that, if you think that makes it cleaner?  The logic: "associated with a singular Message whenever it's exposed, because the transport doesn't do congestion control" seems quite general to me. But I'd be fine with making it UDP specific anyway.

**Comment by gorryfair** [comment]
To me it is datagram specific to connection-less protocols. Really this means UDP in this context. 

Transports that are connection-oriented can have the functionality to check for ECN, enable this, detect and respond to marking and appropriate machinery to decide how to fallback. To me, all of this is a system decision not application. It doesn't appear in the API except for UDP-based services.

**Comment by mirjak** [comment]
Should we have this as protocol specific property then?

**Comment by mwelzl** [comment]
Good idea!
