### ISSUE TITLE
Add state diagram to section "Connection State and Ordering of Operations and Events"

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#466]
Would be nice if someone has time to do some ascii art :-)

**Comment by mwelzl** [comment]
Wouldn't that be exactly fig. 4 in the architecture draft?

Except that, looking at this now, I see inconsistencies!  E.g., I don't see "RendezvousDone" in the figure. Also, instead of ConnectionReceived, it says "Connection Received" - rather, this should probably marked as an event by writing it as "ConnectionReceived<>". The figure is also missing InitiateWithSend() ... probably it would be good to make this figure both complete and consistent with section 13, "Connection State and Ordering of Operations and Events", of the API draft? I don't think very much is missing there.

**Comment by mirjak** [comment]
I think it would be nice to have a real state diagram here, probably with states like "closed", "open" and "listen" and the events that create a transition between these state.

**Comment by britram** [comment]
I'm not sure that Figure 4 in the Arch diagram serves the purpose that Mirja's trying to address with the state diagram in API.

I also don't think we need FIgure 4 to align with the specific naming and CamelCasingConventions in API.
