### ISSUE TITLE
Clean up appendix of API

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#468]
Note: I'm putting this issue in mostly so we remember to discuss at the interim. 

Actions are:
1) I think we need to decide what to do about "Cost Preferences" and then (re)move Appendix B

2) Appendix C can probably be removed or we should point to Theresa's implementation instead (I'm not indicating that Theresa owns this implementation or that she is the only implementor but I think people know what I mean)

3) Clean up Appendix D (Michael? :-) )

**Comment by mwelzl** [comment]
Appendix D: I ACK that I'll to do whatever's needed - but just out of curiosity, what do you mean with "clean up"? I thought it's reasonably clean as it is... of course there may need to be a cleaning pass at the end due to all the changes we're now doing, which may have quite some influence on all the backward references. No problem, I'll fix those. But what else?

**Comment by mwelzl** [comment]
... that said, I think you mean the minset appendix with appendix D? I think this is appendix C, I can't see an appendix D. Similarly, with C you probably mean B.

**Comment by mirjak** [comment]
Ah, it turn out that I looked that the -05 version in the datatracker... too many browser taps...

So I guess you did this already and the part about cost preference is also resolved. So I'll close this issue and have a separate for Appendix B (Sample code in Go).
