### ISSUE TITLE
IANA registry of property names or namespaces - from Kyle Rose's review

### ISSUE THREAD

**Issue by mwelzl** [ietf-tapswg/api-drafts#521]
List discussion:

**Kyle**:
>  If we're not currently asking IANA to create a registry of property names or namespaces, should we provide a recommendation that such symbols not listed explcitly in this document be prefixed with some experimental identifier?

**@philsbn**:
> The IANA registry question was explicitly postponed, be maybe we should re-iterate it now.
> The idea of having an „x“ namespace was rejected in fear we end up with quasi-standard properties that have an x prefix then. 
> 

**Kyle**:
> Which is worse? A complete free-for-all, or a recommendation to have the free-for-all confined to an X- namespace? Do properties starting with X- just offend engineering sensibilities?
> 
> One "right" alternative is a documentation-required registry, but does that raise the bar too high? How about a TAPS wiki as a compromise? The important outcome is that properties be well-defined and not conflict with each other. Since these properties have entirely local effects (e.g., they don't get encoded as options and transmitted to the peer), we probably don't need the level of precision motivating option registries, for instance. Is there precedent at the IETF for a registry mechanism less formal that what IANA provides?
>

**Comment by squarooticus** [comment]
Anyone have any thoughts on this one?

**Comment by gorryfair** [comment]
I see three straw man proposals:
(1) Create a registry of property names or namespaces, AND explIcitly define a range for IANA assignment and a policy...
(2) Recommend a prefix format in the document...
(3) Do nothing and see what happens....
... I think all three are possible ways forward. If TAPS succeeds in having high impact, I suspect we'd like to have done (1).

**Comment by squarooticus** [comment]
This was my thought, as well. If we go with 1, however, we need to either have a low bar (spec required?) to support experimentation. If not, the easy path for implementors will be to invent their own names without documenting them anywhere, which is likely to produce the kinds of problems that the free-for-all in HTTP headers ended up with.

One potential idea is to declare a small set of experimental property names that will inevitably overlap between different implementations: this would enable easy experimentation but require implementors to move to a permanent, unique property name in order to proceed to interop. Thoughts? Maybe this one should be moved to the list.

**Comment by philsbln** [comment]
I am much in favour of @gorryfair's first proposal, as we already have namespaces and a default namespace.
- For the namespace, I would prefer something with a low threshold as "specification required" and explicitly encouraging experiments within vendor namespaces
- For the default namespace, I would prefer RFC required.
If there are enough +1 for this, I can make a PR

**Comment by mirjak** [comment]
I thought the point was that there is really no requirement for all TAPS implementations to use the same name space. Yes, it easier for applications using different TAPS systems when those have at least a similar names. But it's really just a local decision and restricting this more than needed can also be seen as negative when people want to adapt TAPS but don't want to change their existing naming scheme.

**Comment by gorryfair** [comment]
... If we choose no registry - then we deny the possible possible outcome of a vision of some common set of params allowing apps to be common between systems.
 ... If we have a registry of names, the world can still diverge because nobody uses the registry and people use their existing naming scheme, or people fill the registry with flavours.
One choice forces a result one way, the other permits both ways. If I think of the choice this way, I like possibility of common names. Although that sounds like an architectural dream at this moment, I'd argue it to be the right thing to do.

**Comment by mwelzl** [comment]
I give a +1 to @gorryfair's first proposal too - I can't see how defining a namespace can be seen as negative, as people can always decide to ignore it if they really must, as Gorry says - what's the disadvantage with that?  So ... a +1 from me to @philsbn for starting a PR on this (but perhaps post-interim, just in case we get a chance to discuss this)

**Comment by squarooticus** [comment]
I'll give a more specific example of an anti-pattern resulting from an absence of a path to standardization: the mess the sockets API has with respect to differing sockopts and ioctls across different implementations. A free-for-all will reduce the portability of code, make useful documentation harder to write, and result in errors that are repeated over and over again in multiple code bases. If TAPS is to be useful, these problems should be avoided to the degree possible.

**Comment by squarooticus** [comment]
This is minimally addressed by #568.
