### ISSUE TITLE
flushing cache state

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#546]
Section 9.1 of the implementation draft says:
"Applications must have a way to flush protocol cache state if desired. This may be necessary, for example, if application-layer identifiers rotate and clients wish to avoid linkability via trackable TLS tickets or TFO cookies."

However, my understanding is that protocol cache state is not application specific. I don't think a single application should be able to flush protocol specific state that set up based on an interaction with another application. If an application wants to avoid linkability due to TLS or TFO cookies, it should be enough to indicate in the selection properties that use of these feature is not prohibited, no?

**Comment by abrunstrom** [comment]
The scope of caching may be good to discuss. For the particular example I agree that this could have been handled by prohibiting those mechanisms, but i think there may be other situations where you do want the ability to flush the cached state?

**Comment by tfpauly** [comment]
Align with arch text that the boundary can be set by connection groups.

**Comment by mwelzl** [comment]
Should this be closed? The statement quoted above, "Applications must have a way to flush protocol cache state if desired. ..." doesn't seem to exist in the Implementation draft anymore.

I believe the PR that we discussed today may have addressed this (albeit in a different way: clarifying whether state should be sharable or not rather than explicitly flushing). Isn't this good enough?

**Comment by abrunstrom** [comment]
Yes, I think this was resolved by the PR merged today.
