### ISSUE TITLE
How do you add multiple IP addresses/interfaces to an endpoint?

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#571]
what happened if you add multiple addresses or interfaces to an endpoint: Does it overwrite the existing one or not?

**Comment by MaxF12** [comment]
I would say that it does not overwrite but simply add to a list of addresses. This is mostly because for a Listen() the remote endpoint can be used to filter incoming connections and I don't think it makes much sense to only be able to constrain it to a single address.

**Comment by philsbln** [comment]
I agree with @MaxF12 – but we should really make this explicit

**Comment by mirjak** [comment]
Discussion at interim: Clarification is needed. add() during preconnection will overwrite, and add() cannot be used in connection state. Also add a note in the text that e.g. specifying a specific IP address might restrict mobility or use of multiple paths and could cause the connection to fails when the IP address goes way rather than enabling some handover. Still open: Do we need a way to add of multiple addresses in the first place? This is used for filtering remote IP addresses for listener for multicast.

**Comment by tfpauly** [comment]
The current API text doesn't use "add", but rather "with...":

```
RemoteSpecifier := NewRemoteEndpoint()
RemoteSpecifier.WithIPv4Address(192.0.2.21)
RemoteSpecifier.WithPort(443)
```

It also implies that multiple is already allowed:

```
Multiple endpoint identifiers can be specified for each Local Endpoint and
Remote Endpoint.  For example, a Local Endpoint could be configured with two
interface names, or a Remote Endpoint could be specified via both IPv4 and
IPv6 addresses. These multiple identifiers refer to the same transport
endpoint.
```

How does that line up with the comment about `add()`, and having that replace?

**Comment by theri** [comment]
As far as I can see, in the API draft we currently have add() for Properties and Security Parameters where each new add() overwrites the value for the old one.
So if we change this to add(), probably IP addresses should work the same.
But can't we just allow add() with a list of IP addresses instead of just with a single IP address?

**Comment by tfpauly** [comment]
- Allow adding an alias endpoint to an endpoint
- Any one endpoint has at most one hostname
- Any one endpoint has at most one port/service (if you need more, add an alias)
- Any one endpoint has at most one address

If you need multiple source-specific multicast filters, use multiple connection objects

**Comment by mwelzl** [comment]
I'm adding a point from @squarooticus here (and closing a separate issue that he opened, because this tackles the same problem space):

In the past, when I've designed transport abstraction APIs, I've always kept address family abstract, just as BSD sockets do. In this case, you've got WithIPv4Address and With IPv6Address as separate methods on the Endpoint type instead of just a single WithAddress method that takes an object of a type appropriate to the address family.

Similarly, you've got WithPort as a first-class method instead of making it part of the Endpoint, as BSD sockets does with sockaddr_in. What if you want to support both TCP and QUIC, but the QUIC endpoint is on a different port? The notion of "port" is similar between the two, making the use of the same name appropriate, but it is only by convention that they often match: they are completely different spaces implemented in entirely separate codepaths in every network stack. ICMP doesn't even have a port: what if you wanted to use that (or some other port-less protocol that, for instance, multiplexes via IPv6 host ID) with this interface.
