### ISSUE TITLE
Add properties to implementation protocol mappings

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/api-drafts#608]
See discussion on #605

**Comment by abrunstrom** [comment]
Provide a complete template that covers all functions/properties from the API. Indicate how the template should be used (e.g. leave out the parts that are not relevant for a particular protocol or include all fields and mark fields that are not relevant as such.

**Comment by tfpauly** [comment]
I'm wondering if this is really something that's in scope that we should cover. We do have the message properties section that explains how to implement various properties, but I think adding each property to every protocol mapping will be a huge amount of text that will be difficult to get exactly right.

**Comment by abrunstrom** [comment]
I agree, we have added additional properties since we opened this issue to check the mapping and make sure we have a complete coverage. We should still be consistent in how we treat things though, and perhaps add a sentence that we do not describe all the properties for instance. I have made a pass through to check the mapping from the API to impl. draft for all the protocol mappings as a basis for making things consistent. Here is the summary.
- We cover the same actions and events for all the protocols with the exceptions that UDP Multicast does not cover the ConnectionError event and SCTP covers the Priority connection property. And MPTCP and UDP-lite are special as they refer back to the base protocols.
- There is one terminology inconsistency where the impl. draft refers to InitiateError and this has been generalized to EstablishmentError in the API
- Unless I missed something, there are only two actions that can be made on a connection that are not covered, addRemote and removeRemote. This is probably fine as they do not mean much for most of the protocols (or we could add them to be complete). We should perhaps mention how they relate to MPTCP though if we leave them out.
- We also do not cover the Preconnection.Rendezvous action. Again this may be fine as it is a bit special (or we can mention it for consistency.)
- For the events, we cover a subset with main focus on the connection related events. The Closed Event and some events related to connection setup are missing. As we cover ConnectionError we should perhaps cover the Closed event as well? We do not cover any of the Send or Receive events which seems fine.
- In relation to Connection and Message properties, we do not cover any of them except for the Connection priority covered for SCTP and we talk about some properties in connection to UDP-lite and MPTCP. SCTP also has support for partial reliability and unordered messages so not sure why the priority part was singled out and added. @mwelzl any particular reasoning behind this part? Possibly we should remove the priority part for SCTP or discuss it in running text in a similar fashion as for UDP-lite and MPTCP
- We may want to update the UDP-lite description to also say something about what properties it supports over UDP. The current description sounds like it is a subset.

**Comment by mwelzl** [comment]
1. ConnectionError should be added; SCTP priority should be removed
2. Fix the inconsistency
3. Add addRemote and removeRemote text related to MPTCP
4. No action
5. Mention Closed Event
6. See item 1, no further action
7. Update UDP-Lite description
