### ISSUE TITLE
Partial Coverage: Unclear Sentence

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#624]
sec 5.2.7
I am not sure what this sentence means: "Disabling this property may enable to control checksum coverage later."

**Comment by gorryfair** [comment]
This text is confusing in several ways. Before I offer a rewrite, I have some questions, to which I'm sure others will be able to remind me of the reasons we arrived here.
(a) I think the param in 5.2.7 and 5.2.8 may also be about a default for sending and receiving for the established connection, if so... each of these needs to supply an integer as per Section 8.1.3.6...? 
(b) If this isn't to establish the default, and only for influencing the selected protocol for a "connection", why do we have separate send and receive properties for partial coverage? (The only protocols I know can support this for both of the directions...)
(c) I really don't understand how we arrived at "8.1.3.6". I think any practical use will need to be able to set the "Corruption Protection Length" for send and receive independently. Yet we finally only have one parameter.
.... I'd be happy to propose text if someone can restore my understanding of what was intended.

**Comment by mwelzl** [comment]
@gorryfair:
Re: (a): I think this wasn't about an Integer, but about protocol choice (only for influencing the selected protocols, as you say under (b)).
Re: (b): I think this was only a general thing before, and later divided (I don't fully remember why). I think, however, that it's a different thing to say "I'm going to actively race this protocol" and "I'm going to also listen for incoming packets with this protocol". So that's the distinction between these two, IIRC.
Re: (c): What would a "Corruption Protection Length" parameter for receiving accomplish? With UDP-Lite, you only learn about it after the fact, but you can only generally accept to get such packets (as per 5.2.8), but then you can only learn about the length parameter that was used, not influence it, I think.

**Comment by gorryfair** [comment]
OK on (a).
You describe (b) as somewhat useful, maybe the text should say this.

On (c) I still this still needs a send and receive number because SEND Minimum coverage and RECV Minimum coverage are two different things in RFC 3828, Sect 3.3.:

A UDP-Lite receiver does not generally see the coverage value used in datagrams, it therefore needs to configure what min coverage it expects for the receiver stack to check before passing the datagram upwards (this could be per socket/connection). The receiver is probably clearer in RFC5097, Sect 1.3, which counts datagrams with the non-deliverable coverage “EndpointViolCoverage”.  

At the sender, each datagram needs to set an appropriate coverage (this typically needs to be per message).

**Comment by mwelzl** [comment]
Just for the record, I agree with all points of @gorryfair above.

**Comment by gorryfair** [comment]
Thought to now be addressed as a part of PR to API #642
