### ISSUE TITLE
should prop-cc be an enum?

### ISSUE THREAD

**Issue by martinduke** [ietf-tapswg/api-drafts#646]
the api draft currently has congestion control as a Boolean, but it's not quite that simple.
- Some applications might want "least effort" LEDBAT type behavior
- Others might need a warning if the transport can't achieve a certain bit rate.
- To get really fancy, there could be congestion controls parameterized for mobile, lossy links, etc.

The allowed values might be:
{ none, best effort, least effort, fixed bit rate }
or something to that effect.

It's always an option for the application to just do 'none' and implement odd congestion controls in the app, but it would be nice if we could bring high-level qualitative constraints into taps. On other hand existing APIs don't do much of this so perhaps it's too much to take on.

**Comment by mwelzl** [comment]
We have to be careful about prescribing internals to the TAPS system (which takes away implementation flexibility and makes it more likely for the system to fail meeting a request), and focus on describing services instead.

Clearly, "congestion control or not" is a service, because the application really should take care of it if it isn't being offered.
However, if the TAPS system is offering congestion control, then it shouldn't be the application's business to decide whether the TAPS system should implement the things you're asking for via congestion or some other means (and we can always allow to query, for applications that really do care about this level of detail; but for these cases, as you say, it would also be possible to say 'none' and do it exactly as you wish in your application).

So, to be concrete about your points:
- Scavenger-type behavior is encoded as a value of the capacity profile. The text there hints about using a DSCP value, but there should be nothing in the way of a TAPS system implementing this with LEDBAT, or using both LEDBAT and a DSCP value - or whatever other means it may have available.
- This item about the bit rate is covered by the Generic Connection Property "Bounds on Send or Receive Rate".
- Parametrizing congestion control per link is exactly the type of thing an application shouldn't be bothered about, but a TAPS system could automate below, depending on what it knows about the path.  Give it the freedom to do so!

**Comment by martinduke** [comment]
@mwelzl good point -- I didn't appreciate how these other controls interact.
