### ISSUE TITLE
Strange disappearing sentence compilation mistery

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#655]
§4.2: "Although Connection Properties (see Section 7.1) can be set during pre-establishment, they may be changed later."

Four sentences later:

"Connection Properties can be set on Preconnections"

**Comment by mwelzl** [comment]
Unrelated, but about the same text: I notice something weird here, regarding compilation.

Looking at https://ietf-tapswg.github.io/api-drafts/draft-ietf-taps-interface.html  I see:
`They are used to inform decisions made during establishment and to fine-tune the established connection.Section 8.1.3).`
... which is broken at the end.

However, looking at https://github.com/ietf-tapswg/api-drafts/blob/master/draft-ietf-taps-interface.md  I see:
`They are used to inform decisions made during establishment and to fine-tune the established connection.
The behavior of the selected protocol stack(s) when sending Messages is controlled by Message Properties (see {{message-props}}).`

... which is much better.
Since the last manual commit is 2 days ago, this must be a strange compilation mistake.

**Comment by mwelzl** [comment]
PR #673 has addressed Kyle's point - so this is now about something else. Please see my comment above.

**Comment by tfpauly** [comment]
The `.md` file is the correct copy. We can close this.
