### ISSUE TITLE
Partial and interleaved receives

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/api-drafts#669]
§8.3.2.2 says:

> This event does not support delivering discontiguous partial Messages.

What happens if a ReceivedPartial event is dispatched on an unreliably connection, but the rest of the message never shows up? Is it the case that another call to Receive will result in two events being sent: Received (or ReceivedPartial) for the new message, and a ReceiveError for the original message? Or can two messages effectively be interleaved and delivered in whatever order the constituent packets arrive?

**Comment by mwelzl** [comment]
Could you elaborate on the error case that's on your mind?  Because it's unclear to me - I would say that ordering obviously needs to be preserved within a message, while inter-message ordering is a different issue (controlled by the msgOrdered Message Parameter). How is this not clear from saying that delivering discontiguous partial Messages are not supported?

**Comment by squarooticus** [comment]
Let's say you send the following:

M1 M2 M3 N1 N2 N3

where M=M1.M2.M3 is one message and N=N1.N2.N3 is another message. The receiver subsequently gets:

M1 N1 N2 N3

My reading of the draft is that the receiver will see

ReceivedPartial<M1>
ReceivedPartial<N1>
ReceivedPartial<N2>
Received<N3>

If M2 and M3 subsequently arrive, it sounds like the receiver will never get ReceivedPartial<M2> or Received<M3> because "this event does not support delivering discontiguous partial Messages." But what makes the receiving TAPS logic decide not to wait for M2 or M3 and to start delivering N?

**Comment by mwelzl** [comment]
`If M2 and M3 subsequently arrive, it sounds like the receiver will never get ReceivedPartial or Received because "this event does not support delivering discontiguous partial Messages."`

This is not how I would have interpreted the sentence. It talks about the message itself being discontiguous - so, e.g., delivering M1 followed by M3 would never happen. I don't see a reason why a different message couldn't be delivered, in pieces or not, after a ReceivedPartial call - every receive call comes with a message context, so the messages can be separated.

I can try to make this clearer, maybe by adding an example like yours here to the draft....
