### ISSUE TITLE
UDP-Lite and Zero UDP Checksum (sect  6.1.1 and 7.1.3.6)

### ISSUE THREAD

**Issue by gorryfair** [ietf-tapswg/api-drafts#776]
The Required Minimum Corruption Protection Coverage for Receiving  current text says:

   This property specifies the minimum number of bytes in a received
   message that need to be covered by a checksum.  A special value of 0
   means that no checksum is permitted.  A receiving Endpoint will not
   forward messages to the application that have less coverage.  The
   application is responsible for handling any corruption within the
   non-protected part of the message [RFC8085].

- I have thought, and there seem to be various problems with how this finally emerged:

1. in the UDP-Lite API, the. Value 0 indicates full coverage, not zero coverage. If the zero is intentionally redefined this way, what is the expected value for full coverage?
2. The words “No checksum is permitted” can be read in multiple ways.... if this means a message can be received without checking a checksum, then this should be said.
3. Finally, can we specify the receiver outcome when the API requires x bytes of coverage, but the message header protects fewer bytes, is the message discarded, as per UDP-Lite?

Section 7.1.3.6.  Sending Corruption Protection Length,
4. is the zero case interpreted differently to UDP-LIte?
5. Note: I THINK setting the to zero presently forces IPv4, (since UDP for IPv6 requires a checksum except for an upper-layer that explicitly performs this function).

**Comment by mwelzl** [comment]
I have updated your comment to use numbers so I can answer it a little easier here.

1. It's defined as a special value (see: "Type: Integer, with special value Full Coverage"). This answers 4) too: in UDP-Lite, also on sending, "0" indicates full coverage, whereas here it means the opposite "that no checksum is required".
[side note, it says "non-negative" for sending, in 7.1.3.6, but it should say so for receiving, in 6.1.1, as well].

2. I agree.

3. I think this would be good to specify, yes, and I agree that it should be discarded. Clearly, since this is called "*required* minimum corruption protection length", it is a promise that must be kept.

4. see above

5. I'm lost (yes I'm aware that IPv6 has no checksum, but still). Are you talking about 0 as I write here ("no checksum required"), or 0 as in UDP-Lite (requiring full checksum coverage) ?

**Comment by tfpauly** [comment]
Ping @gorryfair
