### ISSUE TITLE
Clarify handling of receive errors

### ISSUE THREAD

**Issue by mirjak** [ietf-tapswg/api-drafts#792]
Actually handling of receive error is also not fully clear to me. Section 7.3.2.3 says:
"A ReceiveError occurs when data is received by the underlying Protocol Stack that cannot be fully retrieved or parsed"

However, I assume that this error should rather not be called if a transport is reliable because the assumption is that the packet will be retransmitted, right?

E.g. in case of QUIC if a packet cannot be decrypted would that trigger an error or not? I assume not, because the QUIC stack cannot even know if a packet contained any payload data, right?

**Comment by mwelzl** [comment]
I agree that this is not very clear - to me, the cases that you describe are cases that should not throw this error, because it's a problem of the underlying protocol and not relevant to the application (what's an application going to do with it anyway?).

I can only see two relevant cases of errors:
1. the one example that we already give: "a Message that was being partially received previously, but had not completed, encountered an error and will not be completed."  - note that this does not assume a fully reliable transfer, because in this case, the underlying stack would solve it, and the fact that there are retransmissions shouldn't be relevant to the application. So this means "you got a partial message from me before, but now I can tell you that you won't get the rest".
2. the case discussed in #776: a minimum checksum coverage range was required for reception, but this promise was not kept => the Transport Services system will have to be discard the incoming message.

There may well be others, but it's probably good to give these two examples, not only one, to make it clearer what kinds of errors are covered by this, and to explicitly state that this is only about errors that are relevant to the application, not protocol-internal reception errors.

**Comment by gorryfair** [comment]
I think this is how I see it. These errors should be actionable by the upper layer, in contrast something that fails an auth check is not actionable by an upper layer protocol.

A different  other use is for logging ... to diagnose fault, where you could want to see what isn’t processed by the lower layers. This is not the use I see here.

Gorry
