### ISSUE TITLE
B.2.3. unreliable-datagram profile

### ISSUE THREAD

**Issue by abrunstrom** [ietf-tapswg/api-drafts#821]
Why are the settings for reliability, preserveOrder, congestionControl Ignore rather than Avoid? The current profile will match SCTP equally well as UDP.

**Comment by gorryfair** [comment]
To me, there are multiple ways a DG service cabn be used. I think there are at least two distinct cases here:
* A datagram usage that WANTS full control, e.g. because something like RTP is layered above that handles these things, and any lower layer additions might interfere with these mechanisms.
* A datagram usage that PREFS no hinderance, but does not mind how these are handled as long as the packets get through - i.e. connects.

**Comment by gorryfair** [comment]
I'm OK with:
reliability | avoid
preserveOrder | avoid
Can't this be ignore?:
congestionControl |  Ignore

**Comment by gorryfair** [comment]
Merged
